version: '2.2'

services:
  app:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
  static:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - app
    links:
      - app

