// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import user "github.com/codenation-dev/squad-4-aceleradev-fs-online-1/backend/pkg/user"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// SignIn provides a mock function with given fields: credentials
func (_m *Service) SignIn(credentials user.Credentials) (string, error) {
	ret := _m.Called(credentials)

	var r0 string
	if rf, ok := ret.Get(0).(func(user.Credentials) string); ok {
		r0 = rf(credentials)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(user.Credentials) error); ok {
		r1 = rf(credentials)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
